[colors.primary]
background = '#16161e'
foreground = '#e0cca8'

[colors.selection]
text = '#e0cca8'
background = '#7dcfff'

[colors.cursor]
text = '#16161e'
cursor = '#8d96bd'

[colors.normal]
black   = '#1a1b26'
red     = '#d96181'
green   = '#5ebd6d'
yellow  = '#ece66a'
blue    = '#7c87b3'
magenta = '#2e3657'
cyan    = '#8D96BD'
white   = '#babcc6'

[colors.bright]
black   = '#7a7c83'
red     = '#ff9fb8'
green   = '#93e2a0'
yellow  = '#fffba5'
blue    = '#a3abcf'
magenta = '#cad2f5'
cyan    = '#e1e7ff'
white   = '#f8f9ff'
