[tools]
go = "latest"
node = "latest"
rust = "latest"
python = "latest"
ripgrep = "latest"
fzf = "latest"
eza = "latest"
zoxide = "latest"
kubectl = "latest"
lazygit = "latest"
neovim = "latest"
zig = "latest"
yazi = "latest"
starship = "latest"
usage = "latest"
